### ISSUE TITLE
Utawareru Mono chinese patched version font wrong

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#7947]
ppsspp
![1](https://cloud.githubusercontent.com/assets/2177532/9706758/982d419a-5522-11e5-9e90-8ddb87152b00.jpg)

jpcsp
![2](https://cloud.githubusercontent.com/assets/2177532/9706760/a380f046-5522-11e5-9656-29c44f7e1f50.jpg)

It need #7941 (@unknownbrackets said break savestates ) and sctrlHENSetStartModuleHandler
log:
https://gist.github.com/sum2012/c7bc1831b6ab2b651834

**Comment by sum2012** [comment]
The sctrlHENSetStartModuleHandler is a hard change from jpcsp to pppsspp (from me)
https://github.com/jpcsp/jpcsp/commit/4aedafdccd8b51881a3be3b64cfe7554740d458d

**Comment by unknownbrackets** [comment]
So basically this function relies on a CFW function to be called before the start module function?

With that and kernel IO we expect it will work?

-[Unknown]

**Comment by sum2012** [comment]
Just log sctrlHENSetStartModuleHandler  ?

**Comment by unknownbrackets** [comment]
Is any source code available for the patch?

Note here:
https://github.com/hrydgard/ppsspp/pull/13335#issuecomment-689026242

In theory, we could create this HEN structure and expose it, as long as it doesn't go to deep into kernel land.  If it needs sceKernelQuerySystemCall, it might get tricky.

-[Unknown]

**Comment by sum2012** [comment]
Chinese patch team never release source code.
Re-test newest version the game become blue screen
log: https://gist.github.com/sum2012/182225c0d3a55729762c77dfa902fd5c
I will open another issue when I get more information

**Comment by unknownbrackets** [comment]
It's still calling sctrlHENSetStartModuleHandler.  But apparently an FPL allocation failed too, which might be because of the module loading another module (not sure.)  The log doesn't include information about FPL allocation failures anymore because that information has been deemed too noisy, so you'd need to mark SCEKERNEL logging as DEBUG to log it now.

-[Unknown]

**Comment by sum2012** [comment]
I have created another issue in #13859

**Comment by benderscruffy** [comment]
Is this still an issue ??

**Comment by sum2012** [comment]
ppsspp v1.13.1-722-g49d5b6447 
Now blue screen 
log:
https://gist.github.com/sum2012/4a14885f7d484a29713c1bb414ef9171

**Comment by Kethen** [comment]
If it's similar to codestation's patcher, it'd be rather hard to get functional, considering it might try to hook `sceIoOpen` `sceIoRead` and `sceIoClose`, on the game module's import table, to try and redirect file IO

https://github.com/codestation/prxpatch/blob/461fcee8906b887d52d0db4f2863aa2dd5447834/mhp3loader/main.c#L42

So I guess the only way to find out is to add `sctrlHENSetStartModuleHandler` and see how that goes, see what more the plugin wants afterwards.

I've also noticed slight oddity with `sceKernelQueryModuleInfo` when working on another plugin, where `SceKernelModuleInfo.text_addr` didn't seem to match up with real devices (0x28 larger than real device on Gran Turismo), while the memory layout seems equivalent. Does not seem to be an issue here with this plugin built into the ISO since it hasn't used that function yet, but keep an eye out for that when testing plugins, if `sctrlHENSetStartModuleHandler` were to be added.

**Comment by Kethen** [comment]
Dumping SceModule again as SceModule2

Gran Turismo PPSSPP
```
module #0 274:
SceKernelModuleInfo:
 size :96
 nsegment: 3
 reserved: 0x0 0x0 0x0
 segmentaddr: 0x8804000 0x8cdc500 0x0 0x0
 segmentsize: 0x4d8488 0x9afac 0x0 0x0
 entry_addr: 0x880410c
 gp_value: 0x8ce9390
 text_addr: 0x8804028
 text_size: 0x477d30
 data_size: 0x10d70
 bss_size: 0x95f0c
 attribute: 0x0
 version: 0x0 0x0
 name: PDIAPP
SceModule2:
 attribute: 0x0
 version: 0x0 0x0
 modname: PDIAPP
 terminal: 0x0
 unknown1: 0x0
 unknown2: 0x0
 modid: 274
 unknown3: 0x0 0x0
 mpid_text: 0x0
 mpid_data: 0x0
 ent_top: 0x8c7b244
 ent_size: 0x10
 stub_top: 0x8c7b25c
 stub_size: 0x2d0
 unknown4: 0x880410c 0x88044e4 0x0 0x0 0x0
 entry_addr: 0x880410c
 gp_value: 0x8ce9390
 text_addr: 0x8804028
 text_size: 0x477d30
 data_size: 0x10d70
 bss_size: 0x95f0c
 nsegment: 3
 segmentaddr: 0x8804000 0x8cdc500 0x0 0x0
 segmentsize: 0x4d8488 0x9afac 0x0 0x0
```

Gran Turismo PSP
```
module #52 65299569:
SceKernelModuleInfo:
 size :96
 nsegment: 2
 reserved: 0x0 0x0 0x0
 segmentaddr: 0x8804000 0x8cdc500 0x0 0x0
 segmentsize: 0x4d8488 0x9afac 0x0 0x0
 entry_addr: 0x880410c
 gp_value: 0x8ce9390
 text_addr: 0x8804000
 text_size: 0x477d30
 data_size: 0x10d70
 bss_size: 0x95f0c
 attribute: 0x0
 version: 0x0 0x0
 name: PDIAPP
SceModule2:
 attribute: 0x0
 version: 0x0 0x0
 modname: PDIAPP
 terminal: 0x0
 unknown1: 0x505
 unknown2: 0x10036
 modid: 65299569
 unknown3: 0xffffffff 0x3e5d301
 mpid_text: 0x2
 mpid_data: 0x2
 ent_top: 0x8c7b244
 ent_size: 0x10
 stub_top: 0x8c7b25c
 stub_size: 0x2d0
 unknown4: 0x880410c 0x88044e4 0xffffffff 0xffffffff 0xffffffff
 entry_addr: 0x880410c
 gp_value: 0x8ce9390
 text_addr: 0x8804000
 text_size: 0x477d30
 data_size: 0x10d70
 bss_size: 0x95f0c
 nsegment: 2
 segmentaddr: 0x8804000 0x8cdc500 0x0 0x0
 segmentsize: 0x4d8488 0x9afac 0x0 0x0
```

Monster Hunter Portable 3rd PPSSPP
```
module #0 274:
SceKernelModuleInfo:
 size :96
 nsegment: 100
 reserved: 0x1 0x0 0x0
 segmentaddr: 0x8804000 0x0 0x0 0x0
 segmentsize: 0x1679d80 0x7c00 0x54700 0x6e00
 entry_addr: 0x88214c8
 gp_value: 0x8a23ec0
 text_addr: 0x8804000
 text_size: 0x15e65c
 data_size: 0xb9874
 bss_size: 0x0
 attribute: 0x0
 version: 0x1 0x1
 name: MonsterHunterPortable3rd
SceModule2:
 attribute: 0x0
 version: 0x1 0x1
 modname: MonsterHunterPortable3rd
 terminal: 0x0
 unknown1: 0x0
 unknown2: 0x0
 modid: 274
 unknown3: 0x0 0x0
 mpid_text: 0x0
 mpid_data: 0x0
 ent_top: 0x8961334
 ent_size: 0x10
 stub_top: 0x896134c
 stub_size: 0x2d0
 unknown4: 0x88214c8 0x88218a4 0x0 0x0 0x0
 entry_addr: 0x88214c8
 gp_value: 0x8a23ec0
 text_addr: 0x8804000
 text_size: 0x15e65c
 data_size: 0xb9874
 bss_size: 0x0
 nsegment: 356
 segmentaddr: 0x8804000 0x0 0x0 0x0
 segmentsize: 0x1679d80 0x7c00 0x54700 0x6e00
```

Monster Hunter Portable 3rd PSP
```
module #51 70333503:
SceKernelModuleInfo:
 size :96
 nsegment: 1
 reserved: 0x0 0x0 0x0
 segmentaddr: 0x8804000 0x0 0x0 0x0
 segmentsize: 0x1679d80 0x0 0x0 0x0
 entry_addr: 0x88214c8
 gp_value: 0x8a23ec0
 text_addr: 0x8804000
 text_size: 0x217ed0
 data_size: 0x0
 bss_size: 0x1461eb0
 attribute: 0x0
 version: 0x1 0x1
 name: MonsterHunterPortable3rd
SceModule2:
 attribute: 0x0
 version: 0x1 0x1
 modname: MonsterHunterPortable3rd
 terminal: 0x0
 unknown1: 0x505
 unknown2: 0x10037
 modid: 70333503
 unknown3: 0xffffffff 0x431224f
 mpid_text: 0x2
 mpid_data: 0x2
 ent_top: 0x8961334
 ent_size: 0x10
 stub_top: 0x896134c
 stub_size: 0x2d0
 unknown4: 0x88214c8 0x88218a4 0xffffffff 0xffffffff 0xffffffff
 entry_addr: 0x88214c8
 gp_value: 0x8a23ec0
 text_addr: 0x8804000
 text_size: 0x217ed0
 data_size: 0x0
 bss_size: 0x1461eb0
 nsegment: 1
 segmentaddr: 0x8804000 0x0 0x0 0x0
 segmentsize: 0x1679d80 0x0 0x0 0x0
```
