### ISSUE TITLE
Curious crashes from the Play Console, part II

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#9774]
Now that we're back up and data is starting to come in again, I'm seeing that the old SW renderer crashes and a few others are completely gone, so that's good. But there are still a few common crashers remaining, I'm going to update this thread with what I find and tag it on solutions.

First out is a pure virtual:
```
backtrace:
  native: pc 00000000000427bc  /system/lib/libc.so (tgkill+12)
  native: pc 00000000000403c9  /system/lib/libc.so (pthread_kill+32)
  native: pc 000000000001caab  /system/lib/libc.so (raise+10)
  native: pc 0000000000019d29  /system/lib/libc.so (__libc_android_abort+34)
  native: pc 000000000001756c  /system/lib/libc.so (abort+4)
  native: pc 00000000009005f7  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN9__gnu_cxx27__verbose_terminate_handlerEv+226)
  native: pc 00000000008c99d5  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN10__cxxabiv111__terminateEPFvvE+4)
  native: pc 00000000008c9a49  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZSt9terminatev+8)
  native: pc 00000000008ca03f  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (__cxa_pure_virtual+14)
  native: pc 000000000030b871  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN22FramebufferManagerGLES14DestroyAllFBOsEv+16)
  native: pc 000000000030321f  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN8GPU_GLESD2Ev+46)
  native: pc 000000000030341d  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN8GPU_GLESD0Ev+4)
  native: pc 000000000035d6f1  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_Z12GPU_Shutdownv+16)
  native: pc 00000000002f42f1  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_Z12PSP_Shutdownv+328)
  native: pc 00000000003b5351  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN9EmuScreenD2Ev+40)
  native: pc 00000000003b550d  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN9EmuScreenD0Ev+4)
  native: pc 0000000000452497  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN13ScreenManager8shutdownEv+42)
  native: pc 00000000003b3337  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_Z14NativeShutdownv+10)
  native: pc 00000000003acb4f  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (Java_org_ppsspp_ppsspp_NativeApp_shutdown+66)
  native: pc 000000000002818d  /data/app/org.ppsspp.ppsspp-1/oat/arm/base.odex
```

This one still happens regularly in 1.4.2:
```
  native: pc 00000000002de334  <unknown>
  native: pc 00000000002845af  /data/app/org.ppsspp.ppsspp-2/lib/arm/libppsspp_jni.so (_Z18__KernelReSchedulePKc+54)
  native: pc 00000000fffffffd  <unknown>
```

More 1.4.2 (and also earlier):
```
 native: pc 0000000000022390  /system/lib/libc.so (memset+24)
 native: pc 000000000022c88b  /mnt/asec/org.ppsspp.ppsspp-1/lib/libppsspp_jni.so
 native: pc 00000000000cf838  <unknown>
```

```
native: pc 0000000000017884  /system/lib/libc.so (strcmp+112)
native: pc 0000000000211f3f  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN9ElfReader8LoadIntoEjb+302)
```

**Comment by unknownbrackets** [comment]
Hmm, can the `__KernelReSchedule` one be a stack overflow or something?  Maybe something bad is happening with mips callbacks, or something.  Not really sure what would be crashing.  Is this definitely 64 bit (seems like it)?

`__KernelLoadELFFromPtr` could take a size.  Maybe we can pass that into `ElfReader` so it can bound check some things?  I feel like `strcmp` is from a corrupted ELF that is not valid.

The `memset`, can't tell....

Feels like the pure virtual call in `DestroyAllFBOs` is memory corruption?

-[Unknown]

**Comment by hrydgard** [comment]
Pure virtuals are usually double-frees or similar destructor issues.

Here's another curious one that I found looking through the realtime crash feed:
```
native: pc 00000000001374f8  <unknown>
  native: pc 00000000001d5e23  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_Z23CallSyscallWithoutFlagsPK11HLEFunction+6)
```

This one gotta be some garbage executed as a display list:
```
  native: pc 0000000000303bde  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN8GPU_GLES11FastRunLoopER11DisplayList+141)
  native: pc 0000000000360e09  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN9GPUCommon13InterpretListER11DisplayList+620)
  native: pc 0000000000361749  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN9GPUCommon22ProcessDLQueueInternalEv+268)
  native: pc 0000000000304e77  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN16ThreadEventQueueI12GPUInterface8GPUEvent12GPUEventTypeLS2_0ELS2_8ELS2_7EE14RunEventsUntilEy+414)
  native: pc 0000000000361aed  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN9GPUCommon14ProcessDLQueueEv+8)
  native: pc 00000000003604e1  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN9GPUCommon11EnqueueListEjji10PSPPointerI13PspGeListArgsEb+1044)
  native: pc 00000000002438dd  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_Z10WrapU_UUIUIXadL_Z16sceGeListEnQueuejjijEEEvv+44)
  native: pc 000000000022a3e3  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_Z23CallSyscallWithoutFlagsPK11HLEFunction+14)
  native: pc 00000000000a5030  <unknown>
```

**Comment by hrydgard** [comment]
```
backtrace:
  native: pc 000000000045c182  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN2UI14DispatchEventsEv+289)
  native: pc 0000000000467d55  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN2UI19UpdateViewHierarchyEPNS_9ViewGroupE+1084)
  native: pc 00000000003c95eb  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN10MainScreen6updateEv+10)
  native: pc 00000000004525db  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN13ScreenManager6updateEv+50)
  native: pc 00000000003b2f7b  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_Z12NativeUpdatev+366)
  native: pc 00000000003acdb5  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (Java_org_ppsspp_ppsspp_NativeRenderer_displayRender+40)
  native: pc 0000000000024a0f  /data/app/org.ppsspp.ppsspp-1/oat/arm/base.odex
```
